name: Compilation

on: [push, pull_request]

jobs:
  compilation:
    name: Compilation Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Build Essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Make project
        run: make -C coders

      - name: Check for relink
        run: |
          make -C coders > first_build.txt
          make -C coders > second_build.txt
          if grep -q "Nothing to be done" second_build.txt || grep -q "up to date" second_build.txt; then
            echo "No relink detected. Good job!"
          else
            echo "Error: Makefile relinks!"
            exit 1
          fi

      - name: Clean project
        run: make fclean -C coders
